stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed
    outs:
      - model.pt